In [1]:
import itertools
import numpy as np

In [6]:
M = [1, 2, 3]
bundle_space = list(itertools.product([0, 1], repeat=len(M)))


In [7]:
print(bundle_space)

[(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1)]


In [12]:
[list(x) + ["!p"] for x in bundle_space]

[[0, 0, 0, '!p'],
 [0, 0, 1, '!p'],
 [0, 1, 0, '!p'],
 [0, 1, 1, '!p'],
 [1, 0, 0, '!p'],
 [1, 0, 1, '!p'],
 [1, 1, 0, '!p'],
 [1, 1, 1, '!p']]

In [22]:
k = 3
bundle_space = [np.random.choice([0, 1], len(M)) for _ in range(k)]
bundle_space = np.unique(np.array(bundle_space), axis=0)
print(bundle_space)


[[0 0 1]
 [0 1 1]
 [1 0 1]]


In [3]:
import pickle
dataset="srvm"
bidder_id=1
nbids=25000
filepath = "./dataset_generation/datasets/"+ str(dataset)+"/"+str(dataset)+"_"+str(bidder_id)+"_"+str(nbids)+".pkl"
with open(filepath, "rb") as file:
    dataset = pickle.load(file)
#split dataset into train and test
if dataset == "gsvm":
    N = 7
    M = 18
if dataset == "lsvm":
    N = 6
    M = 18
print("sucess!") 
    


sucess!


In [4]:
print(len(dataset[0]))
len(dataset[1])

8


8

In [5]:
print(dataset[0][0])

(0, 0, 0)


In [6]:
print(dataset[1][0])

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [7]:
print(dataset[0][100])

IndexError: list index out of range

In [8]:
print(dataset[1][100])

IndexError: list index out of range

In [9]:
from sklearn.model_selection import train_test_split
X = dataset[0]
y = dataset[1]
train_percent = 0.8
X_train, test_and_val_X, y_train, test_and_val_y = train_test_split(X, y, test_size=train_percent, random_state=1)
X_val, X_test, y_val, y_test = train_test_split(test_and_val_X,test_and_val_y, test_size=0.5, random_state=1)


In [10]:
#print(X_train)
print(len(X))
print(len(X[0]))
print(len(X_train[0]))
print(len(y_train[0]))
print(len(y_train))
print(len(X_train.type))


8
3
3
7
1


AttributeError: 'list' object has no attribute 'type'

In [11]:
import torch
X_train_tensor = torch.FloatTensor(X_train).float()
y_train_tensor = torch.FloatTensor(y_train).float()
X_val_tensor = torch.FloatTensor(X_val).float()
y_val_tensor = torch.FloatTensor(y_val).float()
print(X_train_tensor.shape)

torch.Size([1, 3])


In [12]:
batch_size = 4
train_loader = torch.utils.data.DataLoader(X_train_tensor, batch_size=batch_size, shuffle=True)

for batch in train_loader:
    print(batch.shape)
    break


torch.Size([1, 3])


In [13]:
from torch.utils.data import TensorDataset 
train = TensorDataset(X_train_tensor, y_train_tensor)

train_loaderr = torch.utils.data.DataLoader(train, batch_size=batch_size, shuffle=True)

for batch in train_loaderr:
    print(batch[1][:,1].shape)
    break


torch.Size([1])


In [14]:
train[0][1]

tensor([  5.6432,  10.0689,  18.1749, 222.5635, 226.2735, 482.8948, 495.4346])

In [3]:
import pandas as pd

train = pd.read_csv("/dataset_generation/blogfeedback/blogData_train.csv", header=None)



FileNotFoundError: [Errno 2] No such file or directory: '/dataset_generation/blogfeedback/blogData_train.csv'

In [ ]:
train.head()

In [ ]:
# access part of dataframe in pandas 
train.iloc[0:2, 0:2]
# copy part of dataframe to a new dataframe 
train2 = train.iloc[0:2, 0:2].copy()

# copy selection of columns to a new dataframe and remove from original 
train3 = train.iloc[0:2, 0:2].copy()
train.drop(train.columns[[0, 1]], axis=1, inplace=True)
train.head()

In [ ]:
# save dataset with pickle 
import pickle
with open("train.pkl", "wb") as file:
    pickle.dump(train, file)

In [6]:
import pandas as pd
import os 
print(os.getcwd())

train = pd.read_csv("./dataset_generation/compas/compas-scores-raw.csv")



/home/felix/Documents/Masterthesis/ML-CCA-MVNN/compare-models


In [8]:
train 

Person_ID  AssessmentID  Case_ID Agency_Text LastName FirstName  \
0          50844         57167    51950    PRETRIAL   Fisher     Kevin   
1          50844         57167    51950    PRETRIAL   Fisher     Kevin   
2          50844         57167    51950    PRETRIAL   Fisher     Kevin   
3          50848         57174    51956    PRETRIAL  KENDALL     KEVIN   
4          50848         57174    51956    PRETRIAL  KENDALL     KEVIN   
...          ...           ...      ...         ...      ...       ...   
60838      65667         79665    72038   Probation     West     James   
60839      65667         79665    72038   Probation     West     James   
60840      68603         79669    72042    PRETRIAL     Ryan   Michael   
60841      68603         79669    72042    PRETRIAL     Ryan   Michael   
60842      68603         79669    72042    PRETRIAL     Ryan   Michael   

      MiddleName Sex_Code_Text  Ethnic_Code_Text DateOfBirth  ...  \
0            NaN          Male         Caucasian    12/05/92  ...   
1            NaN          Male         Caucasian    12/05/92  ...   
2            NaN          Male         Caucasian    12/05/92  ...   
3            NaN          Male         Caucasian    09/16/84  ...   
4            NaN          Male         Caucasian    09/16/84  ...   
...          ...           ...               ...         ...  ...   
60838        NaN          Male  African-American    06/21/64  ...   
60839        NaN          Male  African-American    06/21/64  ...   
60840        NaN          Male         Caucasian    02/06/85  ...   
60841        NaN          Male         Caucasian    02/06/85  ...   
60842        NaN          Male         Caucasian    02/06/85  ...   

       RecSupervisionLevel             RecSupervisionLevelText Scale_ID  \
0                        1                                 Low        7   
1                        1                                 Low        8   
2                        1                                 Low       18   
3                        1                                 Low        7   
4                        1                                 Low        8   
...                    ...                                 ...      ...   
60838                    3  Medium with Override Consideration        8   
60839                    3  Medium with Override Consideration       18   
60840                    1                                 Low        7   
60841                    1                                 Low        8   
60842                    1                                 Low       18   

                     DisplayText RawScore DecileScore ScoreText  \
0               Risk of Violence    -2.08           4       Low   
1             Risk of Recidivism    -1.06           2       Low   
2      Risk of Failure to Appear    15.00           1       Low   
3               Risk of Violence    -2.84           2       Low   
4             Risk of Recidivism    -1.50           1       Low   
...                          ...      ...         ...       ...   
60838         Risk of Recidivism     0.16           8      High   
60839  Risk of Failure to Appear    35.00          10      High   
60840           Risk of Violence    -2.75           2       Low   
60841         Risk of Recidivism    -0.34           5    Medium   
60842  Risk of Failure to Appear    16.00           2       Low   

      AssessmentType  IsCompleted IsDeleted  
0                New            1         0  
1                New            1         0  
2                New            1         0  
3                New            1         0  
4                New            1         0  
...              ...          ...       ...  
60838            New            1         0  
60839            New            1         0  
60840            New            1         0  
60841            New            1         0  
60842            New            1         0  

[60843 rows x 28 columns]