In [13]:
import itertools
import numpy as np

In [6]:
M = [1, 2, 3]
bundle_space = list(itertools.product([0, 1], repeat=len(M)))


In [7]:
print(bundle_space)

[(0, 0, 0), (0, 0, 1), (0, 1, 0), (0, 1, 1), (1, 0, 0), (1, 0, 1), (1, 1, 0), (1, 1, 1)]


In [12]:
[list(x) + ["!p"] for x in bundle_space]

[[0, 0, 0, '!p'],
 [0, 0, 1, '!p'],
 [0, 1, 0, '!p'],
 [0, 1, 1, '!p'],
 [1, 0, 0, '!p'],
 [1, 0, 1, '!p'],
 [1, 1, 0, '!p'],
 [1, 1, 1, '!p']]

In [22]:
k = 3
bundle_space = [np.random.choice([0, 1], len(M)) for _ in range(k)]
bundle_space = np.unique(np.array(bundle_space), axis=0)
print(bundle_space)


[[0 0 1]
 [0 1 1]
 [1 0 1]]


In [29]:
import pickle
dataset="lsvm"
bidder_id=3
nbids=20
filepath = "./dataset_generation/datasets/"+ str(dataset)+"/"+str(dataset)+"_"+str(bidder_id)+"_"+str(nbids)+".pkl"
with open(filepath, "rb") as file:
    dataset = pickle.load(file)
#split dataset into train and test
if dataset == "gsvm":
    N = 7
    M = 18
if dataset == "lsvm":
    N = 6
    M = 18
    
    


In [36]:
print(len(dataset[0]))
len(dataset[1])

262144


262144

In [37]:
print(dataset[0][0])

(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)


In [38]:
print(dataset[1][0])

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


In [41]:
print(dataset[0][100])

(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0)


In [42]:
print(dataset[1][100])

[24.301122061386828, 14.278913909960313, 22.16300887054362, 19.41352284555659, 25.620134861435606, 31.325488184990274]


In [46]:
from sklearn.model_selection import train_test_split
X = dataset[0]
y = dataset[1]
train_percent = 0.8
X_train, test_and_val_X, y_train, test_and_val_y = train_test_split(X, y, test_size=train_percent, random_state=1)
X_val, X_test, y_val, y_test = train_test_split(test_and_val_X,test_and_val_y, test_size=0.5, random_state=1)


In [61]:
#print(X_train)
print(len(X))
print(len(X[0]))
print(len(X_train[0]))
print(len(y_train[0]))
print(len(y_train))
print(len(X_train.type))


262144
18
18
6
52428


AttributeError: 'list' object has no attribute 'type'

In [64]:
import torch
X_train_tensor = torch.FloatTensor(X_train).float()
y_train_tensor = torch.FloatTensor(y_train).float()
X_val_tensor = torch.FloatTensor(X_val).float()
y_val_tensor = torch.FloatTensor(y_val).float()
print(X_train_tensor.shape)

torch.Size([52428, 18])


In [88]:
batch_size = 4
train_loader = torch.utils.data.DataLoader(X_train_tensor, batch_size=batch_size, shuffle=True)

for batch in train_loader:
    print(batch.shape)
    break


torch.Size([4, 18])


In [93]:
from torch.utils.data import TensorDataset 
train = TensorDataset(X_train_tensor, y_train_tensor)

train_loaderr = torch.utils.data.DataLoader(train, batch_size=batch_size, shuffle=True)

for batch in train_loaderr:
    print(batch[1][:,1].shape)
    break


torch.Size([4])


In [83]:
train[0][1]

torch.Size([6])